<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>

<?php
/**
 * @var $pageTitleBlock \Magento\Theme\Block\Html\Title
 */
$pageTitleBlock = $block->getLayout()->getBlock('page.main.title');
?>

<?php if($pageTitleBlock && trim($pageTitleBlock->getPageHeading())): ?>
    <strong class="fake-title" data-mage-init='{"Magento_Catalog/js/fake-header": {}}'><?php echo $block->escapeHtml($pageTitleBlock->getPageHeading())?></strong>
<?php endif ?>

