<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>

<ul class="product-social-list">
    <li class="product-social-item">
        <a class="product-social-link product-social-facebook" href="#">facebook</a>
    </li>
    <li class="product-social-item">
        <a class="product-social-link product-social-instagram" href="#">instagram</a>
    </li>
    <li class="product-social-item">
        <a class="product-social-link product-social-pinterest" href="#">pinterest</a>
    </li>
</ul>
