<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter">
        <div class="block-title filter-title">
            <strong><?= /* @escapeNotVerified */ __('Shop By') ?></strong>
        </div>

        <div class="block-content filter-content" data-mage-init='{"mage/accordion": {}}'>
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?= /* @escapeNotVerified */ $block->getClearUrl() ?>" class="action clear filter-clear"><span><?= /* @escapeNotVerified */ __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
        <?php if (!$wrapOptions): ?>
            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle" data-mage-init='{"Magento_Catalog/js/filter-slide-toggle": {}}'><?= /* @escapeNotVerified */ __('Shopping Options') ?></strong>
            <dl data-action="filter-slide-content" class="filter-options" id="narrow-by-list" data-role="toggle-content">
                <?php $wrapOptions = true; endif; ?>
                <?php if ($filter->getItemsCount()): ?>
                    <dt role="heading" aria-level="3" class="filter-options-title" data-role="collapsible">
                        <div data-role="trigger"><?= $block->escapeHtml(__($filter->getName())) ?></div>
                    </dt>
                    <dd data-role="content" class="filter-options-content"><?= /* @escapeNotVerified */ $block->getChildBlock('renderer')->render($filter) ?></dd>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions): ?>
            </dl>
        <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
